import type { AuthUser } from '@policymanager/shared';
import type { AuthenticatedApiClient } from '../api-clients/api-client.types';

export type McpIdentity =
  | { kind: 'user'; credential: string; user: AuthUser }
  | { kind: 'api'; credential: string; client: AuthenticatedApiClient };

export interface McpRoute {
  name: string;
  method: string;
  path: string;
  audience: 'user' | 'api' | 'both';
  permissions: string[];
  scopes: string[];
  files?: 'version' | 'manifest' | 'bulk';
  readOnly: boolean;
}

// Reviewed allow-list: never expose a new route merely because it appeared in Swagger.
// mcp.catalog.spec.ts reconciles this list with actual Nest route metadata.
export const MCP_ROUTES: McpRoute[] = [
  {"name":"api_clients_list","method":"GET","path":"/api/api-clients","audience":"user","permissions":["api.manage"],"scopes":[],"readOnly":true},
  {"name":"api_clients_create","method":"POST","path":"/api/api-clients","audience":"user","permissions":["api.manage"],"scopes":[],"readOnly":false},
  {"name":"api_clients_update","method":"PATCH","path":"/api/api-clients/:id","audience":"user","permissions":["api.manage"],"scopes":[],"readOnly":false},
  {"name":"api_clients_revoke","method":"POST","path":"/api/api-clients/:id/revoke","audience":"user","permissions":["api.manage"],"scopes":[],"readOnly":false},
  {"name":"api_clients_rotate","method":"POST","path":"/api/api-clients/:id/rotate-secret","audience":"user","permissions":["api.manage"],"scopes":[],"readOnly":false},
  {"name":"acknowledgments_mine","method":"GET","path":"/api/acknowledgments","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"acknowledgments_acknowledge","method":"POST","path":"/api/acknowledgments/:id/acknowledge","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"document_signoff_approve","method":"POST","path":"/api/documents/:id/approve","audience":"user","permissions":["document.approve"],"scopes":[],"readOnly":false},
  {"name":"document_signoff_attestations","method":"GET","path":"/api/documents/:id/attestations","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"document_signoff_cover_page_pdf","method":"GET","path":"/api/documents/:id/cover-page","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"document_signoff_export_pdf","method":"GET","path":"/api/documents/:id/export","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"document_signoff_distribute","method":"POST","path":"/api/documents/:id/acknowledgments","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":false},
  {"name":"document_signoff_acknowledgment_status","method":"GET","path":"/api/documents/:id/acknowledgments","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":true},
  {"name":"audit_list","method":"GET","path":"/api/audit","audience":"user","permissions":["audit.read"],"scopes":[],"readOnly":true},
  {"name":"auth_change_password","method":"POST","path":"/api/auth/change-password","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"auth_me","method":"GET","path":"/api/auth/me","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"document_acl_list","method":"GET","path":"/api/documents/:id/acl","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":true},
  {"name":"document_acl_add","method":"POST","path":"/api/documents/:id/acl","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"document_acl_remove","method":"DELETE","path":"/api/documents/:id/acl/:aclId","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"document_annotations_list","method":"GET","path":"/api/documents/:documentId/versions/:versionId/annotations","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"document_annotations_create","method":"POST","path":"/api/documents/:documentId/versions/:versionId/annotations","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":false},
  {"name":"document_annotations_resolve","method":"POST","path":"/api/documents/:documentId/versions/:versionId/annotations/:annotationId/resolve","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":false},
  {"name":"document_annotations_reopen","method":"POST","path":"/api/documents/:documentId/versions/:versionId/annotations/:annotationId/reopen","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":false},
  {"name":"document_annotations_soft_delete","method":"DELETE","path":"/api/documents/:documentId/versions/:versionId/annotations/:annotationId","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":false},
  {"name":"document_categories_tree","method":"GET","path":"/api/document-categories","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"document_categories_create","method":"POST","path":"/api/document-categories","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"document_compare_compare","method":"GET","path":"/api/documents/:id/versions/:fromVersionId/compare/:toVersionId","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"document_compare_export","method":"GET","path":"/api/documents/:id/versions/:fromVersionId/compare/:toVersionId/export","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"documents_list","method":"GET","path":"/api/documents","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"documents_reindex_extraction","method":"POST","path":"/api/documents/extraction/reindex","audience":"user","permissions":["storage.manage"],"scopes":[],"readOnly":false},
  {"name":"documents_get","method":"GET","path":"/api/documents/:id","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"documents_retry_extraction","method":"POST","path":"/api/documents/:id/extraction/retry","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_create","method":"POST","path":"/api/documents","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_bulk_review_schedule","method":"POST","path":"/api/documents/bulk-review-schedule","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":false},
  {"name":"documents_update_review_schedule","method":"PATCH","path":"/api/documents/:id/review-schedule","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":false},
  {"name":"documents_update","method":"PATCH","path":"/api/documents/:id","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_add_version","method":"POST","path":"/api/documents/:id/versions","audience":"user","permissions":["document.write"],"scopes":[],"files":"version","readOnly":false},
  {"name":"documents_download","method":"GET","path":"/api/documents/:id/versions/:versionId/download","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"documents_view_url","method":"GET","path":"/api/documents/:id/versions/:versionId/view-url","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"documents_regenerate_rendition","method":"POST","path":"/api/documents/:id/versions/:versionId/rendition","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_version_html","method":"GET","path":"/api/documents/:id/versions/:versionId/html","audience":"user","permissions":["document.read"],"scopes":[],"readOnly":true},
  {"name":"documents_add_html_version","method":"POST","path":"/api/documents/:id/versions/html","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_editor_config","method":"GET","path":"/api/documents/:id/editor-config","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_restore_version","method":"POST","path":"/api/documents/:id/versions/:versionId/restore","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_soft_delete","method":"DELETE","path":"/api/documents/:id","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_restore","method":"POST","path":"/api/documents/:id/restore","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_archive","method":"POST","path":"/api/documents/:id/archive","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"documents_unarchive","method":"POST","path":"/api/documents/:id/unarchive","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":false},
  {"name":"evidence_binder_history","method":"GET","path":"/api/documents/:id/evidence-binders","audience":"user","permissions":["evidence.export"],"scopes":[],"readOnly":true},
  {"name":"evidence_binder_export","method":"POST","path":"/api/documents/:id/evidence-binders/export","audience":"user","permissions":["evidence.export"],"scopes":[],"readOnly":false},
  {"name":"health_check","method":"GET","path":"/health","audience":"both","permissions":[],"scopes":[],"readOnly":true},
  {"name":"imports_import_manifest","method":"POST","path":"/api/imports","audience":"user","permissions":["document.write"],"scopes":[],"files":"manifest","readOnly":false},
  {"name":"imports_import_bulk","method":"POST","path":"/api/imports/bulk","audience":"user","permissions":["document.write"],"scopes":[],"files":"bulk","readOnly":false},
  {"name":"imports_list","method":"GET","path":"/api/imports","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":true},
  {"name":"imports_get","method":"GET","path":"/api/imports/:id","audience":"user","permissions":["document.write"],"scopes":[],"readOnly":true},
  {"name":"notifications_list","method":"GET","path":"/api/notifications","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"notifications_unread_count","method":"GET","path":"/api/notifications/unread-count","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"notifications_preferences","method":"GET","path":"/api/notifications/preferences","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"notifications_update_preferences","method":"PATCH","path":"/api/notifications/preferences","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"notifications_mark_read","method":"PATCH","path":"/api/notifications/:id/read","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"notifications_read_all","method":"PATCH","path":"/api/notifications/read-all","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"notifications_dismiss","method":"DELETE","path":"/api/notifications/:id","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"notifications_run_digest","method":"POST","path":"/api/notifications/digest/run","audience":"user","permissions":["smtp.manage"],"scopes":[],"readOnly":false},
  {"name":"public_documents_list","method":"GET","path":"/api/v1/documents","audience":"api","permissions":[],"scopes":["documents:read"],"readOnly":true},
  {"name":"public_documents_search","method":"GET","path":"/api/v1/search","audience":"api","permissions":[],"scopes":["documents:read","content:read"],"readOnly":true},
  {"name":"public_documents_get","method":"GET","path":"/api/v1/documents/:id","audience":"api","permissions":[],"scopes":["documents:read"],"readOnly":true},
  {"name":"public_documents_content","method":"GET","path":"/api/v1/documents/:id/content","audience":"api","permissions":[],"scopes":["content:read"],"readOnly":true},
  {"name":"public_documents_download","method":"GET","path":"/api/v1/documents/:id/download","audience":"api","permissions":[],"scopes":["download"],"readOnly":true},
  {"name":"public_documents_versions","method":"GET","path":"/api/v1/documents/:id/versions","audience":"api","permissions":[],"scopes":["documents:read"],"readOnly":true},
  {"name":"rag_chat_status","method":"GET","path":"/api/rag/status","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"rag_chat_reindex","method":"POST","path":"/api/rag/reindex","audience":"user","permissions":["storage.manage"],"scopes":[],"readOnly":false},
  {"name":"rag_chat_chat","method":"POST","path":"/api/rag/chat","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"rag_chat_list_conversations","method":"GET","path":"/api/rag/conversations","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"rag_chat_get_conversation","method":"GET","path":"/api/rag/conversations/:id","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"reviewers_list","method":"GET","path":"/api/documents/:id/reviewers","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":true},
  {"name":"reviewers_assign","method":"POST","path":"/api/documents/:id/reviewers","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":false},
  {"name":"reviewers_unassign","method":"DELETE","path":"/api/documents/:id/reviewers/:userId","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":false},
  {"name":"reviews_list","method":"GET","path":"/api/reviews","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"reviews_compliance","method":"GET","path":"/api/reviews/compliance-summary","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":true},
  {"name":"reviews_run_sweep","method":"POST","path":"/api/reviews/run-sweep","audience":"user","permissions":["review.manage"],"scopes":[],"readOnly":false},
  {"name":"reviews_get_task","method":"GET","path":"/api/reviews/tasks/:taskId","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"reviews_complete","method":"POST","path":"/api/reviews/:taskId/complete","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"saved_searches_list","method":"GET","path":"/api/saved-searches","audience":"user","permissions":[],"scopes":[],"readOnly":true},
  {"name":"saved_searches_create","method":"POST","path":"/api/saved-searches","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"saved_searches_update","method":"PATCH","path":"/api/saved-searches/:id","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"saved_searches_run","method":"POST","path":"/api/saved-searches/:id/run","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"saved_searches_remove","method":"DELETE","path":"/api/saved-searches/:id","audience":"user","permissions":[],"scopes":[],"readOnly":false},
  {"name":"smtp_get_config","method":"GET","path":"/api/smtp/config","audience":"user","permissions":["smtp.manage"],"scopes":[],"readOnly":true},
  {"name":"smtp_update_config","method":"PUT","path":"/api/smtp/config","audience":"user","permissions":["smtp.manage"],"scopes":[],"readOnly":false},
  {"name":"smtp_test","method":"POST","path":"/api/smtp/test","audience":"user","permissions":["smtp.manage"],"scopes":[],"readOnly":false},
  {"name":"smtp_notifications","method":"GET","path":"/api/smtp/notifications","audience":"user","permissions":["smtp.manage"],"scopes":[],"readOnly":true},
  {"name":"storage_admin_config","method":"GET","path":"/api/storage/config","audience":"user","permissions":["storage.manage"],"scopes":[],"readOnly":true},
  {"name":"storage_admin_list_buckets","method":"GET","path":"/api/storage/buckets","audience":"user","permissions":["storage.manage"],"scopes":[],"readOnly":true},
  {"name":"storage_admin_create_bucket","method":"POST","path":"/api/storage/buckets","audience":"user","permissions":["storage.manage"],"scopes":[],"readOnly":false},
  {"name":"storage_admin_list_prefixes","method":"GET","path":"/api/storage/prefixes","audience":"user","permissions":["storage.manage"],"scopes":[],"readOnly":true},
  {"name":"storage_admin_create_prefix","method":"POST","path":"/api/storage/prefixes","audience":"user","permissions":["storage.manage"],"scopes":[],"readOnly":false},
  {"name":"roles_list","method":"GET","path":"/api/roles","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":true},
  {"name":"users_list","method":"GET","path":"/api/users","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":true},
  {"name":"users_get","method":"GET","path":"/api/users/:id","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":true},
  {"name":"users_create","method":"POST","path":"/api/users","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
  {"name":"users_update","method":"PATCH","path":"/api/users/:id","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
  {"name":"users_disable","method":"POST","path":"/api/users/:id/disable","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
  {"name":"users_enable","method":"POST","path":"/api/users/:id/enable","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
  {"name":"users_lock","method":"POST","path":"/api/users/:id/lock","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
  {"name":"users_unlock","method":"POST","path":"/api/users/:id/unlock","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
  {"name":"users_reset_password","method":"POST","path":"/api/users/:id/reset-password","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
  {"name":"users_assign_roles","method":"POST","path":"/api/users/:id/roles","audience":"user","permissions":["user.manage"],"scopes":[],"readOnly":false},
];

export const MCP_EXCLUSIONS: { method: string; path: string; reason: string }[] = [
  {"method":"POST","path":"/api/auth/login","reason":"Credential bootstrap; sign in outside model-visible tools"},
  {"method":"POST","path":"/api/auth/refresh","reason":"Credential bootstrap; refresh outside model-visible tools"},
  {"method":"POST","path":"/api/auth/logout","reason":"Credential bootstrap; revoke refresh credentials outside model-visible tools"},
  {"method":"POST","path":"/api/auth/forgot-password","reason":"Credential recovery outside model-visible tools"},
  {"method":"POST","path":"/api/auth/reset-password","reason":"Credential recovery outside model-visible tools"},
  {"method":"GET","path":"/api/auth/oidc/azure","reason":"Browser OIDC redirect protocol"},
  {"method":"GET","path":"/api/auth/oidc/azure/callback","reason":"Browser OIDC callback protocol"},
  {"method":"GET","path":"/api/documents/:id/versions/:versionId/content","reason":"OnlyOffice source protocol; purpose-scoped signed token"},
  {"method":"POST","path":"/api/documents/:id/editor-callback","reason":"OnlyOffice save protocol; signed callback and scoped token"},
];
